### ISSUE TITLE
Получение информации о проиндексированных страницах

### ISSUE THREAD

**Issue by ohmycto** [igor-alexandrov/yandex-webmaster#1]
Игорь, привет, отличный гем, а главное - очень нужный :)

Скажи, ты планируешь реализовать получение информации о проиндексированных страницах (http://api.yandex.ru/webmaster/doc/dg/reference/hosts-indexed.xml)?

**Comment by igor-alexandrov** [comment]
Привет!
Там уже есть серктный метод `host.load_indexed_urls`. Пока пользуйтесь им.

Вообще есть желание реализовать все функции API, сейчас просто дел очень много.

**Comment by ohmycto** [comment]
Ясно, если что с нас пулл реквест!

**Comment by igor-alexandrov** [comment]
Больше всего эта штука понадобится, когда Яндекс запустит Острова.
Можно будет прямо из админки проекта управлять Островами в поисковой выдаче. Вот эта будет действительно круто. Так что давайте делать!

**Comment by dmitry-matveyev** [comment]
На данный момент функция load_indexed_urls падает с ошибкой

TypeError: can't convert Hash into Integer
from /rails_root/vendor/bundle/ruby/1.9.1/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster/api/attributes/writer_builder.rb:23:in `initialize'

в момент обработки ответа от сервера, сам ответ приходит нормально.

Однако, на данный момент апи яндекса возвращает только проиндексированные  страницы за последнюю неделю, и не более 100, что делает использование данной функции бессмысленным.
