### ISSUE TITLE
installation...

### ISSUE THREAD

**Issue by bashu** [igor-alexandrov/yandex-webmaster#2]
Hey,

$ sudo gem install yandex-webmaster  
ERROR:  Error installing yandex-webmaster:
    yandex-webmaster requires yandex-webmaster (>= 0)

I need to pass --force options to install it, you need either update docs or fix gem =)

Thanks!

**Comment by foxweb** [comment]
Same problem.

**Comment by Nakilon** [comment]
bump

**Comment by bashu** [comment]
no one cares
